name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v1

      - name: 下载submodule源码
        run: mv -Force .gitmodules_github .gitmodules && git submodule sync && git submodule update --init

      - name: 配置 vcpkg
        uses: lukka/run-vcpkg@v7
        with:
          vcpkgDirectory: '${{github.workspace}}/vcpkg'
          vcpkgTriplet: x64-windows-static
          # 2024.06.01
          vcpkgGitCommitId: '47364fbc300756f64f7876b549d9422d5f3ec0d3'
          vcpkgArguments: 'openssl libsrtp[openssl] usrsctp ffmpeg'

      - name: 编译
        uses: lukka/run-cmake@v3
        with:
          useVcpkgToolchainFile: true
          buildDirectory: '${{github.workspace}}/build'
          cmakeAppendedArgs: >-
            -DENABLE_API_STATIC_LIB=ON
            -DENABLE_FFMPEG=ON
            -DENABLE_PLAYER=ON
            -DENABLE_SERVER=ON
          cmakeBuildType: 'Release'

      - name: 设置环境变量
        run: |
          $dateString = Get-Date -Format "yyyy-MM-dd"
          $branch = $env:GITHUB_REF -replace "refs/heads/", "" -replace "[\\/\\\?\%\*:\|\x22<>]", "_"
          $branch2 = $env:GITHUB_REF -replace "refs/heads/", ""
          echo "BRANCH=$branch" >> $env:GITHUB_ENV
          echo "BRANCH2=$branch2" >> $env:GITHUB_ENV
          echo "DATE=$dateString" >> $env:GITHUB_ENV

      - name: 打包二进制
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.workflow }}_${{ env.BRANCH }}_${{ env.DATE }}
          path: release/*
          if-no-files-found: error
          retention-days: 90
